## Importing Python modules

In [1]:
from twarc import Twarc2, expansions
import os
import pandas as pd
import requests
import time

## Input your Twitter Bearer Token

In [2]:
TOKEN = "YOUR TWITTER ACADEMIC TRACK BEARER TOKEN"

## Query Parameter (e.g., search keyword, time)

In [3]:
os.environ["BEARER_TOKEN"] = TOKEN
bearer_token = os.environ["BEARER_TOKEN"]

def auth():
    return os.environ.get("BEARER_TOKEN")

next_token = ""
def create_url():
    if next_token == "":
        return "https://api.twitter.com/2/tweets/search/all"
    else: 
        return "https://api.twitter.com/2/tweets/search/all?next_token={}".format(next_token)
    
search_url = create_url()
    
query_params = {'query': "(PRSA OR @PRSA OR #PRSA) lang:en", # search query
                'tweet.fields': "author_id,created_at,public_metrics,in_reply_to_user_id",
                'start_time': "2022-01-01T00:00:00Z", # data collection start time
                'end_time': '2022-01-03T00:00:00Z',   # data collection end time
                'max_results': 300,
                "expansions":"referenced_tweets.id"}

def create_headers(bearer_token):
    headers = {"Authorization": "Bearer {}".format(bearer_token)}
    return headers

def connect_to_endpoint(url, headers, params):
    response = requests.request("GET", search_url, headers=headers, params=params)
    if response.status_code != 200:
        raise Exception(response.status_code, response.text)
    return response.json()

## Crawling Start

In [4]:
df = pd.DataFrame() 
retweet_df_disk = pd.DataFrame() 

next_token = ''
full_text = ''
row = ''

count = 0

full_text_column = []
includes_id = []
includes_retweet = []

while True:
    bearer_token = auth()
    search_url = create_url()
    headers = create_headers(bearer_token)    
    json_response = connect_to_endpoint(search_url, headers, query_params)
    
    tweet = pd.DataFrame.from_dict(json_response['data']) 
    try:
        tweet_1 = tweet.explode('referenced_tweets')
        tweet_1 = tweet_1.referenced_tweets.apply(pd.Series)
        tweet_2 = tweet_1[["id", "type"]]
        tweet_2.columns = ['retweet_id', 'type']
        tweets = pd.concat([tweet, tweet_2], axis=1)
    
        ### data file
        df = pd.concat([df, tweets], axis=1)

        result_count = json_response['meta']['result_count']
        count += result_count
        print(count)
        time.sleep(3.1)

    except KeyError:
        pass
    
    try:
        includes_range = range(len(json_response['includes']['tweets']))
        includes_id = []
        includes_retweet = []
            
        for i in includes_range:
            id_info = json_response['includes']['tweets'][i]['id']
            text = json_response['includes']['tweets'][i]['text']

            includes_id.append(id_info)
            includes_retweet.append(text)
            retweet_df = ''
            retweet_df = pd.DataFrame(list(zip(includes_id, includes_retweet)), 
                       columns =['retweet_id', 'text'])
    
    except KeyError:
        pass
        
    retweet_df_disk = pd.concat([retweet_df_disk, retweet_df], axis=1)
    retweet_df_disk = retweet_df_disk.drop_duplicates()
                
    if 'next_token' in json_response['meta']:
        next_token = json_response['meta']['next_token']
    else:
        break

engagement = df['public_metrics'].apply(pd.Series)
df = pd.concat([df[['id', 'author_id','created_at', 'text', 'type', 'retweet_id']], engagement], axis=1)
final_data = df.merge(retweet_df_disk, on='retweet_id', how='left')
final_data['retweet_account'] = final_data.text_x.str.extract(r'(RT \@\w+)', expand = True)
final_data.text_y.fillna(final_data.text_x, inplace=True)
final_data.type.fillna("original", inplace=True)
final_data['text_z'] = final_data[['retweet_account', 'text_y']].apply(lambda x: ' '.join(x.dropna()), axis=1)
final_data = final_data[['id', 'author_id', 'created_at', 'type', 'retweet_count', 'reply_count', 'like_count', 'quote_count', 'text_z']].rename(columns={"text_z": "text"})
final_data

86

,id,author_id,created_at,type,retweet_count,reply_count,like_count,quote_count,text
0,1477769524011315210,826104766161879044,2022-01-02T22:31:24.000Z,replied_to,0,1,0,0,I didn‚Äôt realised you got tax credits for lyin...
1,1477750903025319937,1433581386112380932,2022-01-02T21:17:25.000Z,replied_to,1,0,5,0,ACCIDENT ALERT EIGHT-Dead this morning at Muse...
2,1477743788793778179,1273894620,2022-01-02T20:49:09.000Z,retweeted,4,0,0,0,RT @PRSA_Roadsafety Let be honest PSV drivers ...
3,1477740238323789831,19198704,2022-01-02T20:35:02.000Z,original,0,0,2,0,"You‚Äôve heard of the ‚ÄúGreat Resignation,‚Äù but a..."
4,1477737600479866884,948674925950328833,2022-01-02T20:24:33.000Z,replied_to,1,0,5,0,ACCIDENT ALERT EIGHT-Dead this morning at Muse...
...,...,...,...,...,...,...,...,...,...
81,1477119968584126464,18586040,2022-01-01T03:30:18.000Z,original,0,0,0,0,[USA] Public Relations Sr. Advisor for Infrast...
82,1477100493830864903,436045478,2022-01-01T02:12:55.000Z,retweeted,1,0,0,0,RT @DWJr16 It has been my honor to serve as 20...
83,1477098881880055814,1049005198860009473,2022-01-01T02:06:31.000Z,original,1,0,4,0,It has been my honor to serve as 2021 @PRSAHea...
84,1477095571777155073,9745402,2022-01-01T01:53:22.000Z,retweeted,5,0,0,0,"RT @PRSA As we close out 2021, we want to take..."
85,1477087462564540422,539649365,2022-01-01T01:21:08.000Z,original,0,0,1,0,üö®Remember to buy your tickets for our Raffle! ...

## Importing User Name from id

In [5]:
client = Twarc2(bearer_token=TOKEN)
user_id_list = final_data["author_id"]
lookup = client.user_lookup(users=user_id_list)

username = []
follower_n = []
following_n = []

for page in lookup:
    result = expansions.flatten(page)
    for user in result:
        username.append(user['username'])
        follower_n.append(user['public_metrics']['followers_count'])
        following_n.append(user['public_metrics']['following_count'])
        
final_data["username"] = username
final_data["follower_count"] = follower_n
final_data["following_count"] = following_n
final_data

,id,author_id,created_at,type,retweet_count,reply_count,like_count,quote_count,text,username,follower_count,following_count
0,1477769524011315210,826104766161879044,2022-01-02T22:31:24.000Z,replied_to,0,1,0,0,I didn‚Äôt realised you got tax credits for lyin...,_postpunkdad,690,426
1,1477750903025319937,1433581386112380932,2022-01-02T21:17:25.000Z,replied_to,1,0,5,0,ACCIDENT ALERT EIGHT-Dead this morning at Muse...,Missy41091460,3,29
2,1477743788793778179,1273894620,2022-01-02T20:49:09.000Z,retweeted,4,0,0,0,RT @PRSA_Roadsafety Let be honest PSV drivers ...,kiela_w,957,793
3,1477740238323789831,19198704,2022-01-02T20:35:02.000Z,original,0,0,2,0,"You‚Äôve heard of the ‚ÄúGreat Resignation,‚Äù but a...",PRSASacramento,2404,1518
4,1477737600479866884,948674925950328833,2022-01-02T20:24:33.000Z,replied_to,1,0,5,0,ACCIDENT ALERT EIGHT-Dead this morning at Muse...,EliasZakayo300,426,1252
...,...,...,...,...,...,...,...,...,...,...,...,...
81,1477119968584126464,18586040,2022-01-01T03:30:18.000Z,original,0,0,0,0,[USA] Public Relations Sr. Advisor for Infrast...,pr_jobs,5820,3292
82,1477100493830864903,436045478,2022-01-01T02:12:55.000Z,retweeted,1,0,0,0,RT @DWJr16 It has been my honor to serve as 20...,PRSAHealth,2277,1577
83,1477098881880055814,1049005198860009473,2022-01-01T02:06:31.000Z,original,1,0,4,0,It has been my honor to serve as 2021 @PRSAHea...,DWJr16,152,1143
84,1477095571777155073,9745402,2022-01-01T01:53:22.000Z,retweeted,5,0,0,0,"RT @PRSA As we close out 2021, we want to take...",alaskaegan,498,438
85,1477087462564540422,539649365,2022-01-01T01:21:08.000Z,original,0,0,1,0,üö®Remember to buy your tickets for our Raffle! ...,UMDearbornPRSSA,661,687

## Export the data as a excel file

In [6]:
final_data.to_excel("Twitter_data.xlsx")

## The most-retweeted content (top 10)

In [6]:
final_data.drop_duplicates(subset = ["text"]).sort_values(by=['retweet_count'], ascending=False)[0:10]

,id,author_id,created_at,type,retweet_count,reply_count,like_count,quote_count,text,username,follower_count,following_count
11,1477677744511201282,424707168,2022-01-02T16:26:42.000Z,retweeted,11,0,0,0,RT @PRSA Happy New Year! Looking forward to a ...,othatnikkiyoung,1813,2870
50,1477383860627386368,350430192,2022-01-01T20:58:55.000Z,retweeted,5,0,0,0,RT @NHSLincsCCG We've opened up more vaccinati...,ANPCatherine,158,823
10,1477679205945012227,4042432272,2022-01-02T16:32:31.000Z,retweeted,5,0,0,0,"RT @PRSA As we close out 2021, we want to take...",PRSAGoldCoast,181,153
2,1477743788793778179,1273894620,2022-01-02T20:49:09.000Z,retweeted,4,0,0,0,RT @PRSA_Roadsafety Let be honest PSV drivers ...,kiela_w,957,793
42,1477495792487350272,965008485795627009,2022-01-02T04:23:42.000Z,retweeted,4,0,0,0,RT @PRaccred Happy New Year! Is earning the AP...,professordavem,615,688
44,1477468387685113856,705395511155695616,2022-01-02T02:34:48.000Z,original,4,2,14,1,Happy New Year! Is earning the APR credential ...,PRaccred,1168,310
71,1477293850435764229,2827544733,2022-01-01T15:01:15.000Z,original,2,0,6,0,#HappyNewYear to our #PAG members! As we begin...,prsa_pag,466,99
5,1477723373279064069,270478924,2022-01-02T19:28:01.000Z,retweeted,2,0,0,0,"RT @PRSA_Roadsafety Chaotic, Madness , crazine...",JesseKenya,4003,1002
54,1477352252692209670,25765161,2022-01-01T18:53:19.000Z,retweeted,2,0,0,0,RT @prsa_pag #HappyNewYear to our #PAG members...,ufgirl81,573,1022
17,1477640029266657282,1274248967644237825,2022-01-02T13:56:50.000Z,retweeted,2,0,0,0,RT @papafavour Many feared dead this morning a...,OuteringRoadKE,2788,2642

## Twitter users who wrote tweets the most about the issue

In [7]:
talktive = final_data['username'].value_counts().reset_index()[0:10].rename({"index": "username", "username": "tweet n"}, axis = 1) 
talktive

          username  tweet n
0          pr_jobs        6
1       TorivoJobs        3
2       PRSAHealth        2
3       usakenshin        2
4  UMDearbornPRSSA        2
5     careersingov        2
6   doctrahanmedia        2
7           DWJr16        2
8   professordavem        2
9      PRSADetroit        1

## Twitter users with the top 10 highest followers (top 10)

In [8]:
final_data.sort_values(by=['follower_count'], ascending=False).drop_duplicates(subset = ["username"])[0:10]

,id,author_id,created_at,type,retweet_count,reply_count,like_count,quote_count,text,username,follower_count,following_count
69,1477305116378210308,14804281,2022-01-01T15:46:01.000Z,original,11,0,33,4,Happy New Year! Looking forward to a brighter ...,PRSA,108449,639
7,1477716078113562634,525005120,2022-01-02T18:59:02.000Z,original,1,0,0,0,.@ValleyMetro is #hiring a MARKETING PRODUCTIO...,careersingov,101035,88385
8,1477715105127321604,16463639,2022-01-02T18:55:10.000Z,retweeted,2,0,0,0,"RT @PRSA_Roadsafety Chaotic, Madness , crazine...",Mwirigi,68541,7737
18,1477639295485853696,385325759,2022-01-02T13:53:55.000Z,original,2,0,2,1,Many feared dead this morning at Musembe along...,papafavour,13182,9905
35,1477543259983417344,2381875884,2022-01-02T07:32:19.000Z,retweeted,1,0,0,0,RT @PRSA_Roadsafety @ntsa_kenya @IG_NPS @NPSC_...,julishwa,6857,4275
14,1477655552629084160,1443305123879530506,2022-01-02T14:58:31.000Z,retweeted,1,0,0,0,RT @usakenshin @Prsa_samurai @nazanin_samurai ...,Okami_mxsamurai,6052,1292
40,1477510026969468937,18586040,2022-01-02T05:20:15.000Z,original,1,0,0,0,[USA] Creative Director (Consumer Public Relat...,pr_jobs,5820,3292
5,1477723373279064069,270478924,2022-01-02T19:28:01.000Z,retweeted,2,0,0,0,"RT @PRSA_Roadsafety Chaotic, Madness , crazine...",JesseKenya,4003,1002
22,1477583250428157953,1210042853340143616,2022-01-02T10:11:13.000Z,retweeted,4,0,0,0,RT @PRSA_Roadsafety Let be honest PSV drivers ...,AccidentAlert_K,3979,99
45,1477464169767133192,41019284,2022-01-02T02:18:02.000Z,quoted,0,0,3,0,Happy New Year! Looking forward to a brighter ...,PRSADetroit,3969,2533